airquality <-datasets::airquality
head(airquality,5)
tail(airquality,10)
summary(airquality)
summary(airquality[,3])
summary(airquality$Temp)
plot(airquality$Ozone)
plot(airquality$Ozone,airquality$Wind)
plot(airquality)
plot(airquality$Ozone,type="h")
plot(airquality$Ozone, xlab='ozone concentration', ylab='no of instances', main='ozone levels in Ny city', col='blue', type= "h")
barplot(airquality$Ozone, xlab='ozone concentration', ylab='no of instances', main='ozone levels in Ny city', col='green', type= "h",horiz = TRUE)
barplot(airquality$Ozone, xlab='ozone concentration', ylab='no of instances', main='ozone levels in Ny city', col='yellow', type= "h")
hist(airquality$Solar.R)
